name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
    - feat
  - title: "🐛 Bug Fixes"
    labels:
      - fix
  - title: "🔧 Chores"
    labels:
      - chore
  - title: "♻️ Refactoring"
    labels:
      - refactor
  - title: "⚡ Performance"
    labels:
      - perf
  - title: "📚 Documentation"
    labels:
      - docs
  - title: "🎨 Style"
    labels: 
      - style
  - title: "🧪 Tests"
    labels:
      - test
  - title: "🏗️ Build"
    labels:
      - build
  - title: "🔌 CI"
    labels:
      - ops
  - title: "⚠️ Breaking Changes"
    labels:
      - breaking
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
no-changes-template: "- No changes"
template: |
  ## What's Changed

  $CHANGES
