services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "db"
      DEBUG: "false"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --no-access-log
    depends_on:
      - db

volumes:
  db_data:
