{
 "title": "Default",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Success API requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"2..\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error API requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"4..|5..\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success outgoing requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(outgoing_http_requests_total{status_code=~\"2..\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error outgoing requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(outgoing_http_requests_total{status_code=~\"4..|5..\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests latency, sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1h]) / rate(http_request_duration_seconds_count[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}