name: CI
on: [workflow_dispatch]

env:
  DEBUG: false
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_TEST_DB: ${{ secrets.POSTGRES_TEST_DB }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  BAS_USERNAME: ${{ secrets.BAS_USERNAME }}
  BAS_PASSWORD: ${{ secrets.BAS_PASSWORD }}
  CAPGURU_KEY: ${{ secrets.CAPGURU_KEY }}
  CAPMONSTER_KEY: ${{ secrets.CAPMONSTER_KEY }}

jobs:
  services:
    postgres:
      image: postgres:17-alpine
    ports:
    - "5432:5432"
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
      - name: Setup python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
        cache: poetry
      - run: poetry install

    tests:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Run tests
          run: make tests

    lint:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Run linter
          run: make lint

    typecheck:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Run typecheck
          run: make typecheck
