name: CI

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "poetry.lock"
      - "pyproject.toml"
      - "Makefile"
    tags-ignore:
      - '**'
  workflow_dispatch:

env:
  DEBUG: false
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  LOKI_HOST: ${{ secrets.LOKI_HOST }}
  LOKI_PORT: ${{ secrets.LOKI_PORT }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  BAS_USERNAME: ${{ secrets.BAS_USERNAME }}
  BAS_PASSWORD: ${{ secrets.BAS_PASSWORD }}
  CAPGURU_KEY: ${{ secrets.CAPGURU_KEY }}
  CAPMONSTER_KEY: ${{ secrets.CAPMONSTER_KEY }}

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: "3.13.0"
          poetry-version: "1.8.4"

      - name: Run tests
        run: |
          source .venv/bin/activate
          make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: "3.13.0"
          poetry-version: "1.8.4"

      - name: Run linter
        run: |
          source .venv/bin/activate
          make lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: "3.13.0"
          poetry-version: "1.8.4"

      - name: Run typecheck
        run: |
          source .venv/bin/activate
          make typecheck
