name: Release Drafter

on:
  workflow_run:
    workflows: 
      - CI
    types:
      - completed
    branches:
      - main

jobs:
  update_release_draft:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
