name: Release after CI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  update_release_with_ci:
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest

    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
